### ISSUE TITLE
As a user concerned with safety and ease of access. I want to create a biometric authentication with haptic feedback, backed up with a pin for easier secure access.

### ISSUE THREAD

**Issue by stiwari98** [UB-CSE/CSE442_a2_teambald#15]
Acceptance Test:

-Have a setting page to change on and off for biometric authentication
-With positive biometrics, the user should be able to sign-in and get into the main page.
-The app loads all history and saved data to the new device after sign-in.

**Comment by baichengchen** [comment]
User story #7

**Comment by baichengchen** [comment]
Acceptance Test:

-Have a setting page to change on and off for biometric authentication
-With positive biometrics, the user should be able to sign-in and get into the main page.
-The app loads all history and saved data to the new device after sign-in.
