### ISSUE TITLE
Currently the filename is hard_coded, need to assign new name each time.

### ISSUE THREAD

**Issue by IVClub** [UB-CSE/CSE442_a2_teambald#17]
Task Test:
 

1. Look over options to resolve file conflict.

2. Go to the File Manager of the Testing Device, make sure each voice record is assigned to the desired but distinct file name.

3. Make sure the newly added file is correctly stored and the previous recordings are not lost after the procedure.

**Comment by KartikeyaDas** [comment]
Make Task tests in the format of the ones that are shown in your lectures, and the one test that's on here.

**Comment by IVClub** [comment]
Got it, will change
