### ISSUE TITLE
As a user who have no knowledge about the App, I want an user-friendly interface for recording storage so that I don't need to do extra operations.

### ISSUE THREAD

**Issue by IVClub** [UB-CSE/CSE442_a2_teambald#24]
1) Audio files between Cloud storage should have a logical synchronization mechanism.
2) Ideally audio can be played without having a local copy of the Audio file.
3) Automatically backup the local audio recording to the cloud.

**Comment by KartikeyaDas** [comment]
Why does the user story have something that a developer should worry about?
